### ISSUE TITLE
Error: DOMXPath::query(): Invalid expression in selector 

### ISSUE THREAD

**Issue by Yaco** [hypeJunction/Elgg-notifications_html_handler#1]
hi!
I get the following error after pressing the "Send email" button on the plugin admin page:

```
DOMXPath::query(): Invalid expression in selector >> .elgg-river-item input[type=text] << in /elgg/mod/notifications_html_handler/vendor/pelago/emogrifier/Classes/Emogrifier.php on line 370
```

Any help? thx!

**Comment by hypeJunction** [comment]
Make sure dom PHP extension is enabled

**Comment by Yaco** [comment]
I think its enabled, since dom extension seems to be compiled-in php. See:

```
$ php -m
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dba
dom
...
```
I also included the line ```extension=dom.so ``` in my php.ini. Iam using ```php-fpm```

The error is still there... Is there any way to check if the extension is being loaded in my php instance?

thx!

**Comment by Yaco** [comment]
This is the full error trace debug:

```
Exception at time 1500306368: exception 'InvalidArgumentException' with message 'DOMXPath::query(): Invalid expression in selector >> .elgg-river-item input[ty
pe=text] << in /srv/reevo-web/www/red/mod/notifications_html_handler/vendor/pelago/emogrifier/Classes/Emogrifier.php on line 370' in /srv/reevo-web/www/red/mod/notifications_html_handler/vendor/pelago/emogrifier/C
lasses/Emogrifier.php:1532
Stack trace:
#0 [internal function]: Pelago\Emogrifier->handleXpathError(2, 'DOMXPath::query...', '/srv/reevo-web/...', 370, Array)
#1 /srv/reevo-web/www/red/mod/notifications_html_handler/vendor/pelago/emogrifier/Classes/Emogrifier.php(370): DOMXPath->query('//*[contains(co...')
#2 /srv/reevo-web/www/red/mod/notifications_html_handler/vendor/pelago/emogrifier/Classes/Emogrifier.php(289): Pelago\Emogrifier->process(Object(DOMDocument))
#3 /srv/reevo-web/www/red/mod/notifications_html_handler/start.php(319): Pelago\Emogrifier->emogrify()
#4 [internal function]: notifications_html_handler_format('format', 'notification', Object(Elgg\Notifications\Notification), Array)
#5 /srv/reevo-web/www/red/vendor/elgg/elgg/engine/classes/Elgg/PluginHooksService.php(52): call_user_func_array('notifications_h...', Array)
#6 /srv/reevo-web/www/red/vendor/elgg/elgg/engine/lib/elgglib.php(827): Elgg\PluginHooksService->trigger('format', 'notification', Array, Object(Elgg\Notifications\Notification))
#7 /srv/reevo-web/www/red/mod/notifications_html_handler/start.php(48): elgg_trigger_plugin_hook('format', 'notification', Array, Object(Elgg\Notifications\Notification))
#8 [internal function]: notifications_html_handler_send_email_notification('send', 'notification:em...', false, Array)
#9 /srv/reevo-web/www/red/vendor/elgg/elgg/engine/classes/Elgg/PluginHooksService.php(52): call_user_func_array('notifications_h...', Array)
#10 /srv/reevo-web/www/red/vendor/elgg/elgg/engine/classes/Elgg/Notifications/NotificationsService.php(496): Elgg\PluginHooksService->trigger('send', 'notification:em...', Array, false)
#11 /srv/reevo-web/www/red/vendor/elgg/elgg/engine/classes/Elgg/Notifications/NotificationsService.php(292): Elgg\Notifications\NotificationsService->sendNotification(Object(Elgg\Notifications\InstantNotificationE
vent), 55, 'email', Array)
#12 /srv/reevo-web/www/red/vendor/elgg/elgg/engine/classes/Elgg/Notifications/NotificationsService.php(398): Elgg\Notifications\NotificationsService->sendNotifications(Object(Elgg\Notifications\InstantNotification
Event), Array, Array)
#13 /srv/reevo-web/www/red/vendor/elgg/elgg/engine/lib/notification.php(513): Elgg\Notifications\NotificationsService->sendInstantNotifications(Object(ElggSite), Array, Array)
#14 /srv/reevo-web/www/red/mod/notifications_html_handler/actions/notifications/html/test.php(18): notify_user(55, 1, 'Test email from...', '<h1>HTML Ipsum ...', Array, 'email')
#15 /srv/reevo-web/www/red/vendor/elgg/elgg/engine/classes/Elgg/Includer.php(18): include('/srv/reevo-web/...')
#16 /srv/reevo-web/www/red/vendor/elgg/elgg/engine/classes/Elgg/ActionsService.php(176): Elgg\Includer::includeFile('/srv/reevo-web/...')
#17 /srv/reevo-web/www/red/vendor/elgg/elgg/engine/lib/actions.php(22): Elgg\ActionsService->execute('notifications/h...')
#18 [internal function]: _elgg_action_handler(Array, 'action')
#19 /srv/reevo-web/www/red/vendor/elgg/elgg/engine/classes/Elgg/Router.php(100): call_user_func('_elgg_action_ha...', Array, 'action')
#20 /srv/reevo-web/www/red/vendor/elgg/elgg/engine/classes/Elgg/Application.php(436): Elgg\Router->route(Object(Elgg\Http\Request))
#21 /srv/reevo-web/www/red/vendor/elgg/elgg/engine/classes/Elgg/Application.php(384): Elgg\Application->run()
#22 /srv/reevo-web/www/red/index.php(8): Elgg\Application::index()
#23 {main}

```
